version = 3.11.1
runner.dialect = scala212source3
project.layout = StandardConvention
maxColumn = 120
spaces.inImportCurlyBraces = true
docstrings.style = keep
indent.defnSite = 2
rewrite.trailingCommas.style = keep
